import { InputValidationRules } from '../../../utils/validation';
import type { IFields } from '../../../utils/validation';

export const CompanyProfileFormSchema: IFields = {
  name: {
    title: 'name',
    rule: InputValidationRules.StringRequired,
    defaultValue: '',
    placeHolder: 'Enter company name',
    label: 'Company Name',
    isRequired: true,
  },
  email: {
    title: 'email',
    rule: InputValidationRules.Email,
    defaultValue: '',
    placeHolder: 'Enter email address',
    label: 'Email',
    isRequired: false,
  },
  contactEmail: {
    title: 'contactEmail',
    rule: InputValidationRules.Email,
    defaultValue: '',
    placeHolder: 'Enter contact email',
    label: 'Contact Email',
    isRequired: false,
  },
  contactNumber: {
    title: 'contactNumber',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter contact number',
    label: 'Contact Number',
    isRequired: false,
  },
  telephone: {
    title: 'telephone',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter telephone number',
    label: 'Telephone',
    isRequired: false,
  },
  mobile: {
    title: 'mobile',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter mobile number',
    label: 'Mobile',
    isRequired: false,
  },
  addressLine1: {
    title: 'addressLine1',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Address line 1',
    label: 'Address Line 1',
    isRequired: false,
  },
  addressLine2: {
    title: 'addressLine2',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Address line 2',
    label: 'Address Line 2',
    isRequired: false,
  },
  addressLine3: {
    title: 'addressLine3',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Address line 3',
    label: 'Address Line 3',
    isRequired: false,
  },
  town: {
    title: 'town',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter town / city',
    label: 'Town / City',
    isRequired: false,
  },
  country: {
    title: 'country',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter country',
    label: 'Country',
    isRequired: false,
  },
  postcode: {
    title: 'postcode',
    rule: InputValidationRules.String,
    defaultValue: '',
    placeHolder: 'Enter postcode',
    label: 'Postcode',
    isRequired: false,
  },
};
